ersion: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./_maps/index.html:/app/index.html
      - ./_maps/map.css:/app/map.css
      - ./_maps/map.js:/app/map.js
